config/routes.rb
Timedsales::Application.routes.draw do
  resources :sales

  match 'login'              => 'login#index',        :as => :login
  match 'login/authenticate' => 'login#authenticate', :as => :authenticate
  match 'login/finalize'     => 'login#finalize',     :as => :finalize
  match 'login/logout'       => 'login#logout',       :as => :logout
  root :to                   => 'home#index'

  match ':controller(/:action(/:id(.:format)))'
end

app/models/sale.rb
class Sale < ActiveRecord::Base

	belongs_to :shop

	attr_accessor :start_delay
	attr_accessor :end_delay

	def timers
		@start_delay = self.start
		@end_delay = self.end
		start_sale
		end_sale
	end

	def start_sale
		@shop = Shop.find(self.shop_id)

		ShopifyAPI::Session.temp(@shop.name, @shop.token) do
			sale = ShopifyAPI::Variant.find(self.variant)
			sale.compare_at_price = sale.price
			sale.price = self.price
			sale.status = "active"
			sale.save
		end
	end
	handle_asynchronously :start_sale, :run_at => Proc.new { |s| s.start_delay }

	def end_sale
		@shop = Shop.find(self.shop_id)

		ShopifyAPI::Session.temp(@shop.name, @shop.token) do
			sale = ShopifyAPI::Variant.find(self.variant)
			sale.price = sale.compare_at_price
			sale.compare_at_price = nil
			sale.status = "previous"
			sale.save
		end
	end
	handle_asynchronously :end_sale, :run_at => Proc.new { |s| s.end_delay }

	validates :product, :presence => true
	validates :variant, :presence => true
	validates :price, :presence => true
	validates :start, :presence => true, :date => { :after => Time.now }
	validates :end, :presence => true, :date => { :after => :start }

end 

app/controllers/sales_controller.rb
class SalesController < ApplicationController

  around_filter :shopify_session

  respond_to :html, :json, :js

  # GET /sales/new
  # GET /sales/new.json
  def new
    @sale = Sale.new
    respond_with(@sale)
  end

  def show
    @sale = Sale.find(params[:id])

    @names = Hash.new
    if !@sale.nil? 
      product = @sale.product
      product_name = ShopifyAPI::Product.find(product, :params => {:fields => "title"})
      @names[product] = product_name

      variant = @sale.variant
      variant_name = ShopifyAPI::Variant.find(variant, :params => {:fields => "title"})
      @names[variant] = variant_name 
    end
  end

  # POST /sales
  # POST /sales.json
  def create
    #set time zone
    Time.zone = Shop.find_by_name(session[:shop_name]).timezone
    Chronic.time_class = Time.zone

    @sale         = Sale.new
    @sale.product = params[:product]
    @sale.variant = params[:variant]
    @sale.start   = Chronic.parse(params[:start_date] + " " + params[:start_time])
    @sale.end     = Chronic.parse(params[:end_date] + " " + params[:end_time])
    @sale.price   = params[:sale_price]
    @sale.shop_id = Shop.find_by_name(session[:shop_name]).id
    @sale.status  = "upcoming"

    respond_to do |format|
      if @sale.save
        # queue up the sale in delayed_job
        @sale.timers
        
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render json: @sale, status: :created, location: @sale }
      else
        format.js { respond_with(@sale.errors) }
      end
    end
  end

  def destroy
    @sale = Sale.find(params[:id])
    @sale.destroy
    respond_with(@sale) do |format|
      format.js { render :nothing => true }
    end
  end

end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale, :html => {:class => "nice"}) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/_sale.html.erb
			<tr style="display:none;">

              <td><%= !@names[@sale.product].title.nil? ? @names[@sale.product].title : nil %></td>
              <td><%= !@names[@sale.variant].title.nil? ? @names[@sale.variant].title : nil %></td>
              <td><%= !@sale.start.nil? ? @sale.start.to_formatted_s(:long_with_time) : nil %></td>
              <td><%= !@sale.end.nil? ? @sale.end.to_formatted_s(:long_with_time) : nil %></td>
              <td><%= number_to_currency(@sale.price, :unit => "$") %></td>
              <td><%= link_to "Delete", sale_path(@sale), :remote => true, :method => :delete, :confirm => 'Are you sure?', :class => "small white button radius deletebutton" %></td>
            </tr>

app/views/sales/create.js.erb
// Create a list of errors
  $("#flasherrors").remove();

  var errors = $('<ul />');

  <% @sale.errors.full_messages.each do |error| %>
    errors.append('<li><%= escape_javascript(error) %></li>');
  <% end %>

  // Display errors before the form
  $('<div id="flasherrors" class="alert-box alert" style="display:none;"><%= flash[:error] %> />').html(errors).appendTo("#new_sale").fadeIn();

app/views/sales/destroy.js.erb
var success = true;

app/views/sales/show.js.erb
<% if @sale.errors.any? %>

  // Create a list of errors
  var errors = $('<ul />');

  <% @sale.errors.full_messages.each do |error| %>
    errors.append('<li><%= escape_javascript(error) %></li>');
  <% end %>

  // Display errors before the form
  $('<div id="flasherrors" class="alert-box warning"><%= flash[:error] %> />').html(errors).prependTo("#new_sale");

<% else %>

  $('<%= j(render(:partial => "sale", :object => @sale))%>').prependTo(".upcoming tbody").fadeIn();

    if ($(".upcoming-flash").length > 0) {
      $(".upcoming-flash").remove();
    }
  // empty the form for new submission
  $("form").find('input:text,textarea,select').val('');
<% end %>